//------------------------------------------------------------------------------
// <auto-generated>
//    
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketManagement.BLL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TicketManagementEntities : DbContext
    {
        public TicketManagementEntities()
            : base("name=TicketManagementEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<pParameter> pParameter { get; set; }
        public virtual DbSet<sRole> sRole { get; set; }
        public virtual DbSet<sSystemObject> sSystemObject { get; set; }
        public virtual DbSet<sUser> sUser { get; set; }
        public virtual DbSet<sUserAccess> sUserAccess { get; set; }
        public virtual DbSet<sUserRole> sUserRole { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tRequest> tRequest { get; set; }
        public virtual DbSet<tRequestComment> tRequestComment { get; set; }
        public virtual DbSet<tRequestHistory> tRequestHistory { get; set; }
    }
}
